spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_network?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Lucvip2003@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  cors:
    allowed-origins: "*"
  security:
    jwt-secret: "family-super-secret-key-change-this-in-production-family-super-secret"
    access-token-seconds: 86400
